/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves_rpc.h"
#include "imp_clave.h"

bool_t
rpc_init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	*result = init();

	return retval;
}

bool_t
rpc_set_value_1_svc(int key, char *value1, int N_value2, vector_value2 value2, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	*result = set_value(key, value1, N_value2, value2.vector_value2_val);

	return retval;
}

bool_t
rpc_get_value_1_svc(int key, get_exit_args *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	result->result = get_value(key, result->value1, &(result->N_value2), result->value2);

	return retval;
}

bool_t
rpc_modify_value_1_svc(int key, char *value1, int N_value2, vector_value2 value2, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	*result = modify_value(key, value1, N_value2, value2.vector_value2_val);

	return retval;
}

bool_t
rpc_delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	*result = delete_key(key);

	return retval;
}

bool_t
rpc_exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	*result = exist(key);

	return retval;
}

int
claves_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
