/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "claves.h"
 //#include "claves_rpc.h"

char* obtener_ip() {
	char* ip;
	ip = getenv("IP_TUPLAS");
	if (ip == NULL) {
		perror("NOT setted ip");
	}
	else {
		return ip;
	}
}

CLIENT* create_clnt(char* host) {
	CLIENT* clnt = clnt_create(host, CLAVES, CLAVESVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	return clnt;
}

void init() {
	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_1;
	int result_1;
	clnt = create_clnt(ip);
	retval_1 = init_rpc_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}

void set_value(int key, char* value1, int N_value2, double* V_value2) {
	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_2;
	int result_2;
	struct params set_value_rpc_1_param;

	// Rellenar struct con argumentos
	set_value_rpc_1_param.key = key;
	strcpy(set_value_rpc_1_param.value1, value1);
	set_value_rpc_1_param.N_value2 = N_value2;
	for (int i = 0; i < N_value2; i++) {
		set_value_rpc_1_param.value2[i] = V_value2[i];
	}

	clnt = create_clnt(ip);
	retval_2 = set_value_rpc_1(set_value_rpc_1_param, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}
void get_value(int key, char* value1, int* N_value2, double* V_value2) {
	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_3;
	int result_3;
	struct params get_value_rpc_1_param;

	// Rellenar struct con argumentos
	get_value_rpc_1_param.key = key;
	strcpy(get_value_rpc_1_param.value1, value1);
	get_value_rpc_1_param.N_value2 = *N_value2;
	for (int i = 0; i < *N_value2; i++) {
		get_value_rpc_1_param.value2[i] = V_value2[i];
	}

	clnt = create_clnt(ip);
	retval_3 = get_value_rpc_1(get_value_rpc_1_param, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}
void delete_key(int key) {
	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_5;
	int result_5;
	struct params delete_key_rpc_1_param;

	// Rellenar struct con argumentos
	delete_key_rpc_1_param.key = key;

	clnt = create_clnt(ip);
	retval_5 = delete_key_rpc_1(delete_key_rpc_1_param, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}
void modify_value(int key, char* value1, int N_value2, double* V_value2) {


	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_4;
	int result_4;
	struct params modify_value_rpc_1_param;

	// Rellenar struct con argumentos
	modify_value_rpc_1_param.key = key;
	strcpy(modify_value_rpc_1_param.value1, value1);
	modify_value_rpc_1_param.N_value2 = N_value2;
	for (int i = 0; i < N_value2; i++) {
		modify_value_rpc_1_param.value2[i] = V_value2[i];
	}

	clnt = create_clnt(ip);
	retval_4 = modify_value_rpc_1(modify_value_rpc_1_param, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}
void exist(int key) {
	char* ip = obtener_ip();
	CLIENT* clnt;
	enum clnt_stat retval_6;
	int result_6;
	struct params exist_rpc_1_param;

	// Rellenar struct con argumentos
	exist_rpc_1_param.key = key;

	clnt = create_clnt(ip);
	retval_6 = exist_rpc_1(exist_rpc_1_param, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
	clnt_destroy(clnt);
}
