/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_rpc.h"

bool_t
xdr_vector_value2 (XDR *xdrs, vector_value2 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vector_value2_val, (u_int *) &objp->vector_value2_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_exit_args (XDR *xdrs, get_exit_args *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value1, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value2, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_set_value_1_argument (XDR *xdrs, rpc_set_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector_value2 (xdrs, &objp->value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_modify_value_1_argument (XDR *xdrs, rpc_modify_value_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector_value2 (xdrs, &objp->value2))
		 return FALSE;
	return TRUE;
}
