/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_rpc.h"

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value2, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
