/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"
#include <stdio.h>
#include "claves_rpc.h"
#include <unistd.h>


void
claves_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int rpc_set_value_1_key;
	char *rpc_set_value_1_value1;
	int rpc_set_value_1_N_value2;
	vector_value2 rpc_set_value_1_value2;
	enum clnt_stat retval_3;
	get_exit_args result_3;
	int rpc_get_value_1_key;
	enum clnt_stat retval_4;
	int result_4;
	int rpc_modify_value_1_key;
	char *rpc_modify_value_1_value1;
	int rpc_modify_value_1_N_value2;
	vector_value2 rpc_modify_value_1_value2;
	enum clnt_stat retval_5;
	int result_5;
	int rpc_delete_key_1_key;
	enum clnt_stat retval_6;
	int result_6;
	int rpc_exist_1_key;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES, CLAVESVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif

	retval_1 = rpc_init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = rpc_set_value_1(rpc_set_value_1_key, rpc_set_value_1_value1, rpc_set_value_1_N_value2, rpc_set_value_1_value2, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = rpc_get_value_1(rpc_get_value_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = rpc_modify_value_1(rpc_modify_value_1_key, rpc_modify_value_1_value1, rpc_modify_value_1_N_value2, rpc_modify_value_1_value2, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = rpc_delete_key_1(rpc_delete_key_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = rpc_exist_1(rpc_exist_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	
}

int
main (int argc, char *argv[]){
	double tres[] = { 3.3,33.3,333.3 };
    int N;
    char cd[] = "cd";
    char texto[256];
    int rn;
    double rvec[32];
    char hello[] = "Hello world";
    double vec5[] = {1.1, 2.2, 3.3, 4.4, 5.5};

    printf("INIT:\n");
    init();
    sleep(1);

    int retorno = -1; 
    retorno = set_value(3, cd, 3, tres);
    printf("first set: %d\n", retorno); 
    sleep(1);
    retorno = set_value(9, cd, 3, tres);
    printf("snd set: %d\n", retorno);
    sleep(1);


    get_value(3, texto, &rn, rvec);
    printf("get_value:\n\ttexto: %s\n\tN: %d\n\tdoubles:", texto, rn);
    for (int i = 0; i < rn; ++i) {
        printf("\n\t\t[%d]: %lf", i, rvec[i]); 
    }
    printf("\n");

    sleep(1);
    
    modify_value(3, hello, 5, vec5);
    get_value(3, texto, &rn, rvec);
    printf("first_modify:\n\ttexto: %s\n\tN: %d\n\tdoubles:", texto, rn);
    for (int i = 0; i < rn; ++i) {
        printf("\n\t\t[%d]: %lf", i, rvec[i]); 
    }
    printf("\n");
    retorno = modify_value(5, cd, 3, tres);
    printf("snd modify: %d\n", retorno);
    
    delete_key(3);
    printf("exits: %i\n", exist(9));
    printf("exits: %i\n", exist(3));
    return 0;
}
